# Generated by Django 5.0.4 on 2024-04-18 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseSchedules',
            fields=[
                ('courseSchedule_Id', models.AutoField(primary_key=True, serialize=False)),
                ('days', models.CharField(max_length=30)),
                ('startTime', models.TimeField()),
                ('endTime', models.TimeField()),
                ('roomNo', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('student_Id', models.AutoField(primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('course_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=300)),
                ('instructor_name', models.CharField(max_length=150)),
                ('capacity', models.IntegerField()),
                ('prerequisites', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='RegiCourse_App.courses')),
                ('schedule', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='RegiCourse_App.courseschedules')),
            ],
        ),
        migrations.CreateModel(
            name='StudentsReg',
            fields=[
                ('studentReg_Id', models.AutoField(primary_key=True, serialize=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RegiCourse_App.courses')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RegiCourse_App.students')),
            ],
        ),
    ]
