# Generated by Django 5.0.4 on 2024-04-20 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegiCourse_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='prerequisites',
            field=models.OneToOneField(blank='True', null=True, on_delete=django.db.models.deletion.CASCADE, to='RegiCourse_App.courses'),
        ),
    ]
