# Generated by Django 5.0.4 on 2024-04-14 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegiCourse_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('course_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=300)),
                ('instructor_name', models.CharField(max_length=150)),
                ('capacity', models.IntegerField()),
                ('prerequisites', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='RegiCourse_App.courses')),
            ],
        ),
        migrations.CreateModel(
            name='CourseSchedules',
            fields=[
                ('courseSchedule_ID', models.AutoField(primary_key=True, serialize=False)),
                ('days', models.CharField(max_length=30)),
                ('startTime', models.TimeField()),
                ('endTime', models.TimeField()),
                ('roomNo', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('student_ID', models.AutoField(primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='StudentsReg',
            fields=[
                ('studentReg_ID', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.DeleteModel(
            name='member',
        ),
        migrations.AddField(
            model_name='courses',
            name='scheduleId',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='RegiCourse_App.courseschedules'),
        ),
        migrations.AddField(
            model_name='studentsreg',
            name='courseId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RegiCourse_App.courses'),
        ),
        migrations.AddField(
            model_name='studentsreg',
            name='studentId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RegiCourse_App.students'),
        ),
    ]
