# Generated by Django 5.0.4 on 2024-04-20 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegiCourse_App', '0002_alter_courses_prerequisites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='prerequisites',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RegiCourse_App.courses'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='schedule',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='RegiCourse_App.courseschedules'),
        ),
    ]
