# Generated by Django 5.0.4 on 2024-05-12 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegiCourse_App', '0002_students_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentsReg',
            fields=[
                ('studentReg_Id', models.AutoField(primary_key=True, serialize=False)),
                ('completed', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RegiCourse_App.courses')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RegiCourse_App.students')),
            ],
        ),
    ]
