# Generated by Django 5.0.4 on 2024-04-14 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RegiCourse_App', '0002_courses_courseschedules_students_studentsreg_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='scheduleId',
            new_name='schedule_Id',
        ),
        migrations.RenameField(
            model_name='courseschedules',
            old_name='courseSchedule_ID',
            new_name='courseSchedule_Id',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='student_ID',
            new_name='student_Id',
        ),
        migrations.RenameField(
            model_name='studentsreg',
            old_name='courseId',
            new_name='course_Id',
        ),
        migrations.RenameField(
            model_name='studentsreg',
            old_name='studentReg_ID',
            new_name='studentReg_Id',
        ),
        migrations.RenameField(
            model_name='studentsreg',
            old_name='studentId',
            new_name='student_Id',
        ),
    ]
