# Generated by Django 5.0.4 on 2024-05-21 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RegiCourse_App', '0003_studentsreg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='notifications',
        ),
    ]
