# Generated by Django 5.0.4 on 2024-04-23 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegiCourse_App', '0003_alter_courses_prerequisites_alter_courses_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsreg',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
