# Generated by Django 5.0.4 on 2024-04-14 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RegiCourse_App', '0003_rename_scheduleid_courses_schedule_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='schedule_Id',
            new_name='schedule',
        ),
        migrations.RenameField(
            model_name='studentsreg',
            old_name='course_Id',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='studentsreg',
            old_name='student_Id',
            new_name='student',
        ),
    ]
