# Generated by Django 5.0.4 on 2024-04-16 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegiCourse_App', '0004_rename_schedule_id_courses_schedule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
