# Generated by Django 5.0.4 on 2024-04-27 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegiCourse_App', '0004_studentsreg_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='students',
            name='notifications',
            field=models.ManyToManyField(blank=True, to='RegiCourse_App.notification'),
        ),
    ]
